### ISSUE TITLE
Implement <vaadin-nav>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-tabs#2]
### Task List

- Work on top of the preview version
- MVP
  - [ ] `vaadin-nav` `vaadin-nav-item`
  - [ ] `nav` rovin-tabindex, horizonal-vertical directions
  - [ ] `nav-item` focus-ring, focused, active, selected
  - [ ] Accessibility support
  - [ ] Keyboard navigation
  - [ ] Search by first letter
- [ ] Themability support
  - [ ] add parts and default themes (discuss with Jouni)
- [ ] Add unit tests
- [ ] Integrate in the Bakery app
- [ ] API documentation + parts & state attrs docs
- [ ] Demos `vaadin-demo-item`(naming undecided, only for the demos for now)
- [ ] Add visual tests
- [ ] Support all required browsers
- [ ] UX/DX tests & fix beta-blocking findings
