### ISSUE TITLE
First alpha version

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-tabs#3]
See specs from #2
UX/DX in a separate task

### Task List (taken from #2)

  - [x] `vaadin-nav` `vaadin-nav-item`
  - [x] `nav` rovin-tabindex, horizonal-vertical directions
  - [x] `nav-item` focus-ring, focused, active, selected
  - [x] Accessibility support
  - [x] Keyboard navigation
  - [x] Search by first letter
- [x] (manolo) Themability support
  - [x] rename attr direction to vertical
  - [x] nav need the attribute `overflow="start|end"`
  - [x] navigation buttons should be visible in vertical
  - [x] no scrollbars visible in any direction, but could be overridable by theming
  - [x] theme might decide if buttons are always hidden
  - [x] (jouni working in a PR) add parts and default themes
- [x] API documentation + parts & state attrs docs (depends on Themability)
- [x] Add unit tests
- [x] Demos `vaadin-demo-item`(naming undecided, only for the demos for now)
- [x] Add visual tests
- [x] Support all required browsers
- [x] Remove `resize` event listener and use `IronResizableBehavior` instead
